[package]
name = "slint_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.13.1"
regex = "1.11.1"
slint = "1.8.0"
ubi = "0.6.1"

[build-dependencies]
slint-build = "1.8.0"
