name: Rust

on:
  push:
    tags:
    - 'v*'
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            command: build

          # - os-name: Windows-x86_64
          #   runs-on: windows-latest
          #   target: x86_64-pc-windows-gnu
          #   command: build

    runs-on: ${{ matrix.platform.runs-on }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish artifacts and release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/slint_calc"
          tag: ${{ github.ref_name }}
