name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build linux
      run: cargo build --release --verbose
    - name: Build windows
      run: cross build --release --target x86_64-pc-windows-gnu
