name: Rust

on:
  push:
    tags:
    - 'v*'
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary linux
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-unknown-linux-musl
          args: "--release"
          strip: true

      - name: Build binary linux
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: x86_64-pc-windows-gnu
          args: "--release"
          strip: true

      - name: Publish artifacts and release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/x86_64-pc-windows-gnu/release/slint_calc.exe,target/x86_64-unknown-linux-musl/release/slint_calc"
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          allowUpdates: true